#!/bin/bash
source $(get-lib-path func/exit-error)
path=$1

if [[ -z $path ]]; then
	exit-error "missing path argument"
fi

function convert-mingw {
	dir_path=$(cd 2>/dev/null "$1" && pwd -W 2>/dev/null)
	realpath -m "${dir_path:-$1}" | \
	sed -r \
		-e 's|^/([a-z])/|\1:/|I' \
		-e 's|/+|/|g' \
		-e 's|/$||' \
		-e 's|/|\\|g'
}

case "$(run-lib get-win-env)" in
cygwin) cygpath -w "$path" ;;
wsl) wslpath -w "$path" ;;
mingw) convert-mingw "$path" ;;
*) exit-error "unsupported Windows environment type" ;;
esac

