#!/bin/bash
source $(get-lib-path func/exit-error)
path=$1

if [[ -z $path ]]; then
	exit-error "missing path argument"
fi
if run-lib is-cygwin; then
	cygpath -u "$path"
else
	if grep -iq '^[a-z]:' <<< "$path"; then
		root=''
		if [[ $(run-lib get-win-env) == wsl ]]; then
			root='/mnt'
		fi
		path="$root/$(sed -re 's|^([a-z]):|\l\1|I' <<< "$path")"
	fi
	cd 2>/dev/null "$path" && pwd || \
	sed -re 's|\\|/|g' -e 's|/+|/|g' -e 's|/$||' <<< "$path"
fi

