#!/bin/bash
source $(get-lib-path func/exit-error)
path=$1

if [[ -z $path ]]; then
	exit-error "missing path argument"
fi
if run-lib is-cygwin; then
	cygpath -u "$path"
else
	cd 2>/dev/null "$path" && pwd || \
	echo $path | sed -re 's|\\|/|g' -e 's|^([a-z]):/|/\1/|I' -e 's|/+|/|g' -e 's|/$||'
fi
