#!/bin/bash
source $(get-lib-path func/exit-error)
path=$1

if [[ -z $path ]]; then
	exit-error "missing path argument"
fi

function convert-mingw {
	path=$1
	if grep -iq '^[a-z]:' <<< "$path"; then
		path="/$(sed -re 's|^([a-z]):|\l\1|I' <<< "$path")"
	fi
	cd 2>/dev/null "$path" && pwd || \
	sed -re 's|\\|/|g' -e 's|/+|/|g' -e 's|/$||' <<< "$path"
}

case "$(run-lib get-win-env)" in
cygwin) cygpath -u "$path" ;;
wsl) wslpath -w "$path" ;;
mingw) convert-mingw "$path" ;;
*) exit-error "unsupported Windows environment type" ;;
esac

