#!/bin/bash

cd $HOME

env=$(run-lib get-win-env)
if [[ -n $env && $env != wsl ]]; then
	app_data=$(convert-path -p "$(run-lib get-win-var APPDATA)")
	local_app_data=$(convert-path -p "$(run-lib get-win-var LOCALAPPDATA)")

	vsc_dir=$app_data/Code/User
	mkdir -p $vsc_dir

	vsc_settings=$vsc_dir/settings.json
	vsc_keybindings=$vsc_dir/keybindings.json
	test ! -e $vsc_settings && symlink .config/Code/User/settings.json $vsc_settings
	test ! -e $vsc_keybindings && symlink .config/Code/User/keybindings.json $vsc_keybindings

	term_dir=$local_app_data/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState
	mkdir -p $term_dir

	term=$term_dir/settings.json
	test ! -e $term && symlink .config/WindowsTerminal/settings.json $term
fi
