#!/bin/bash

# Windows-style option needs to be escaped in MingW
# or else it turns into a path.
if run-lib is-cygwin; then
	slash_k=/K
else
	slash_k=//K
fi

command_string=''
if [[ $# > 0 ]]; then
	command_string="&& $1"
	for arg in "${@:2}"; do
		command_string="$command_string \"$arg\""
	done
fi

sudo.ps1 cmd.exe $slash_k \
	cd "$(convert-path -w $(pwd))" \
	$command_string

