#!/bin/bash
source $(get-func-path exit-error)
source $(get-func-path win-cli-option)

function usage {
cat <<EOF
usage: $(basename $0) TARGET [LINK]
	TARGET: the target of the symlink.
	LINK: the path to the symlink to create.
EOF
}

target=$1
[[ -n $target ]] || exit-usage-error "missing target path"
[[ -e $target ]] || exit-usage-error "target path does not exist"

if [[ -z $(run-lib get-win-env) ]]; then
	ln -s "$@"
	exit $?
fi

if [[ -d $target ]]; then
	dir_arg=$(/ D)
else
	dir_arg=''
fi

if [[ $# < 2 ]]; then
	link=$(basename "$target")
else
	link=$2
fi

target=$(convert-path -w "$(realpath "$target")")
link=$(convert-path -w "$(realpath "$link")")

cmd.exe $(/ C) mklink $dir_arg "$link" "$target" \
|| run-lib sudo-cmd mklink $dir_arg "$link" "$target"

